### PR TITLE
Support both Angular 4 & 5

### PR DESCRIPTION
**Pull request by mdentremont**

### CODE REVIEW

**Comment by langley-agm** [comment]
Remove the version number change please, npm should handle it when making the release.

**Comment by mdentremont** [comment]
@langley-agm :+1:

**Comment by mdentremont** [comment]
@langley-agm Anything else I can do, or is it good to go?

**Comment by fmpierce** [comment]
I hope this gets merged soon.

**Comment by langley-agm** [comment]
@mdentremont an apology, I haven't had access to my pc for a while, lost my charger, I've been traveling and whatnot, if you guys have tested it and it works feel free to do the release so you don't have to wait, otherwise I have my personal laptop and charger now so I'll try my best to do it this weekend. I'll also try to make a guide on how to release so people don't have to wait for me in these scenarios. again I'm sorry !

**Comment by langley-agm** [comment]
Merged and published, should be good now Guys, let me know if any issues arise !

@mdentremont @fmpierce

**Pull request merged**
