### PR TITLE
improve package.json

### PR DESCRIPTION
**Pull request by k7sleeper**
Improve `package.json` to have a proper `main` and `typings` attribute.

Setting the `main` attribute in `package.json` to `core.js` enables client code to write `import {Logger} from "angular2-logger";` instead of `import {Logger} from "angular2-logger/core";`. Angular2 folks do the same.

Setting the `typings` attribute in `package.json` to `core.d.ts` let's the TypeScript compiler use `core.d.ts` when compiling `import {Logger} from "angular2-logger";`. That's what's needed to avoid compiling whole angular2-logger sources. Angular2 folks do the same. They set the `typings` attribute in `package.json`.

### CODE REVIEW

**Comment by langley-agm** [comment]
@k7sleeper what do you mean by Angular folks do the same? 

https://angular.io/docs/ts/latest/quickstart.html

I see them importing from the core module just like I am: `import { Component } from '@angular/core';`

**Comment by langley-agm** [comment]
@k7sleeper I tried these changes but #39 is still occurring, did this fixed it for you?

**Comment by k7sleeper** [comment]
No, these changes alone did not fix #39. You also have to delete *.ts file in `app\core`. So, the final solution must be that angular2-logger creates only one `.d.ts` or angular2-logger distribution does not contain the `.ts` files.

**Comment by k7sleeper** [comment]
Well, if you carefully look at `import { Component } from '@angular/core';`you'll see that `@angular/core`is a **package** whereas `angular2-logger/core` is a file!

`import { Component } from '@angular/core';` is resolved by the `main` attribute in `@angular/core/package.json`.

**Comment by k7sleeper** [comment]
Has this PR a chance to be merged?

**Comment by langley-agm** [comment]
@k7sleeper I thought you said this didnt fix the defect ?

**Comment by k7sleeper** [comment]
@langley-agm Yes, you're right. The defect is solved for me by the following steps which I put into a Grunt task of my build script:

- insert attribute `"typings": "core.d.ts"` into `package.json`
- change attribute `main`to `"core.js"` in `package.json`
- remove all *.ts files from `app` folder

So, if you'd merge this PR I can remove the first 2 patches from my Grunt tasks and generally, `package.json` would increase in quality.

For the last issue I could send another PR but I have no idea how to omit the `*.ts` files from the published package.

**Comment by langley-agm** [comment]
I'm confused, does this solve the defect or not? What defect do you want to solve with this PR ?

**Comment by k7sleeper** [comment]
I'm sorry. I think of #39.

This PR would solve the first 2 issues of the above mentioned list.

**Comment by langley-agm** [comment]
Like I mentioned before, I already ran the code in this PR and it does not solve #39 .

**Comment by k7sleeper** [comment]
Ah, yes your're right. Sorry.

All the time I'm working with `import {Logger} from "angular2-logger"`which I prefer, but that's not what you've documented. So, my way isn't the right.

Anyway, I think merging this PR increases quality of `package.json`, isn't it?

**Comment by langley-agm** [comment]
This PR changes both the package.json and the Guide. 

The Guide works just as Angular 2 does: `import { Component } from '@angular/core';` not `import { Component } from '@angular';` so I'd prefer to leave it as it is right now.

**Comment by k7sleeper** [comment]
Oh yes, you're right. I oversaw the changes in the guide.
I think it's time now to close this PR.

**Pull request closed without merging**
